apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nyxai

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - rbac.yaml
  - service.yaml
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: nyxai
  app.kubernetes.io/managed-by: kustomize

images:
  - name: nyxai/nyxai
    newTag: latest

configMapGenerator:
  - name: nyxai-config
    behavior: merge
    literals:
      - ENVIRONMENT=production

secretGenerator:
  - name: nyxai-secrets
    behavior: merge
    literals:
      - ENVIRONMENT=production
